/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Measurements used on this site
 */
export interface Measurement {
  name: string;
  notes?: string;
  /**
   * a number describing this measurements value in ounces
   */
  equivalence: number;
  unit?: string;
  [k: string]: unknown;
}
